BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    country_code = request.args.get("country_code", default="", type=str)
    states = []
    if country_code.strip():
        states = pycountry.subdivisions.get(country_code=country_code.strip())
    print(f"Found [{len(states)}] states for country_code [{country_code}]")
    if not states:
        states = []
    states = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        states))
    return json.dumps(states)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}

<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label for="name" class="form-label">name</label>
                <input id="name" class="form-control" name="name" type="text" value="">
            </div>
            
            <div class="form-group mb-3">
                <label for="address" class="form-label">address</label>
                <input id="address" class="form-control" name="address" type="text" value="">
            </div>

            <div class="form-group mb-3">
                <label for="city" class="form-label">city</label>
                <input id="city" class="form-control" name="city" type="text" value="">
            </div>
            
            <div class="form-group mb-3">
                <label for="website" class="form-label">website</label>
                <input id="website" class="form-control" name="website" type="url" value="">
            </div>

            <div class="form-group mb-3">
                <label for="zip" class="form-label">zip</label>
                <input id="zip" class="form-control" name="zip" type="text" value="">
            </div>
            {{country_state_selector()}}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
{% from "company_dropdown.html" import company_dropdown %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">

            <div class="form-group mb-3">
                <label for="first_name" class="form-label">first_name</label>
                <input id="first_name" class="form-control" name="first_name" type="text" value="">
            </div>
            
            <div class="form-group mb-3">
                <label for="last_name" class="form-label">last_name</label>
                <input id="last_name" class="form-control" name="last_name" type="text" value="">
            </div>
            
            <div class="form-group mb-3">
                <label for="email" class="form-label">email</label>
                <input id="email" class="form-control" name="email" type="email" value="">
            </div>
        
            {# use the below for company selection #}
            {{ company_dropdown() }}
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% macro company_dropdown(val="") %}
{% set comps = get_companies() %}
{# TODO DO NOT EDIT #}
<select class="form-select mb-3" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>
{% endmacro %}

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% macro country_state_selector(country="", state="", layout="vertical") %}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" required onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}" required>
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>
{% endmacro %}

BusinessManagement/templates/edit_company.html
{% extends "layout.html" %}
{% block title %}Edit Company{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}

<div class="container-fluid">
    <div class="h1">Edit Company</div>
    <div>
        <form method="POST">
            <div class="form-group">
                <label for="name">name*</label>
                <input type="text" class="form-control" id="name"
                name="name" value="{{row.name}}" >
            </div>
            <div class="form-group">
                <label for="address">address*</label>
                <input type="text" class="form-control" id="address"
                name="address" value="{{row.address}}" >
            </div>
            <div class="form-group">
                <label for="website">website*</label>
                <input type="text" class="form-control" id="website"
                name="website" value="{{row.website}}" >
            </div>
            <div class="form-group">
                <label for="city">city*</label>
                <input type="text" class="form-control" id="city"
                name="city" value="{{row.city}}" >
            </div>

            {# use this for country/state selection #}
            {{country_state_selector(country=row.country, state=row.state)}}

            <div class="form-group">
                <label for="zip">zip*</label>
                <input type="text" class="form-control" id="zip"
                name="zip" value="{{row.zip}}" >
            </div>
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/edit_employee.html
{% extends "layout.html" %}
{% block title %}Edit Employee{% endblock %}
{% block content %}
{% from "company_dropdown.html" import company_dropdown %}

<div class="container-fluid">
    <div class="h1">Edit Employee</div>
    <div>
        <form method="POST">
            <div class="form-group">
            <label for="first_name">First Name*</label>
                <input type="text" class="form-control" id="first_name"
                name="first_name" value="{{row.first_name}}" >
            </div>
            <div class="form-group">
                <label for="last_name">Last Name*</label>
                <input type="text" class="form-control" id="last_name"
                name="last_name" value="{{row.last_name}}" >
            </div>
            <div class="form-group">
                <label for="email">Email*</label>
                <input type="email" class="form-control" id="email"
                name="email" value="{{row.email}}" >
            </div>

            <div class="form-group">
                <label for="company">Company</label>
                {{ company_dropdown(row.company_id) }}
            </div>
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/flash.html
{# TODO DO NOT EDIT #}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

BusinessManagement/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Ducks In a Row</div>
    <div class="w-50 mx-auto bg-light text-center caption border">
        At Ducks In A Row, we help
        organize your companies and employees all in one simple dashboard.
    </div>
    <div class="lead text-center">Brought to you by Aneesh (al762 ) from section IS601
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace both with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }

        /* Add style here that'll capitalize all form labels */
    </style>
    <title>{% block title %}{% endblock %} - MP3</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        {% include "nav.html" %}
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-auto" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2023.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (show as company name but name field should be name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit (default 10)
    ensure all fields prefill with request arg data if provided
    #}
    <form method="GET">
        <div class="row">
            <div class="col">
                <input id="name" class="form-control" placeholder="name" name="name" type="text" value="">
            </div>

            {{country_state_selector(layout="horizontal")}}
            {{sort_filter(cols=[("name", "name"), ("address", "address"), ("city", "city"), ("country", "country"), ("state", "state"), ("zip", "zip"), ("Website", "website"), ("employees","employees")])}}
            <div class="col">
                <input id="limit" class="form-control" placeholder="limit" name="limit" type="number" value="10">
            </div>
            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            {% if rows and rows|length > 0 %}
            <thead>
                <tr class="text-capitalize">
                    {# generate th tags for each column to display #}
                    {# IMPORTANT use table column names as the headings, replace _ with space via filter #}
                    
                    {% for col in allowed_columns %}
                    <th>{{ col[1] }}</th>
                    {% endfor %}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {# generate tr with td tags for each piece of data #}
                {# if the td is for website, display it as a link where the text is "website" and the url is the
                website url #}
                {# in the last column add the following
                a view button that passes the company id to employee search (this will be a company employee
                directory) also pass company_name as an argument
                an edit button that passes the company id to company edit
                a delete button that passes the company id and the request args to the company delete route
                #}

                {% for row in rows %}
                <tr>
                    {% for col in allowed_columns %}
                    {% if col[0] == 'website' %}
                    <td>
                        <a href="{{ row['website'] }}">website</a>
                    </td>
                    {% else %}
                    <td>{{ row[col[0]] }}</td>
                    {% endif %}
                    {% endfor %}
                    <td>
                        <a href="/company/edit?id={{ row['id'] }}">Edit</a>
                        <a href="/company/delete?id={{ row['id'] }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="100%">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/list_employees.html
{% extends "layout.html" %}
{% block title %}Employee Directory{% endblock %}
{% block content %}
{% from "company_dropdown.html" import company_dropdown %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">{{request.args.get("company_name","")}} Employee Directory</div>
    <form method="GET">
        {# TODO
        build a horizontal filter/sort form with
        first_name (show as first name, but name should be fn)
        last_name (show as last name, but name should be ln)
        email (validate as text, not email, so partial match works)
        company (provided) (name is company value is the id)
        sort/order (using allowed_columns and provided partial template)
        limit (default 10)
        ensure all fields prefill with request arg data if provided
        #}

        <div class="row">
            <div class="col">
                <input id="fn" class="form-control" placeholder="fn" name="fn" type="text" value="">
            </div>
            <div class="col">
                <input id="ln" class="form-control" placeholder="ln" name="ln" type="text" value="">
            </div>             
            <div class="col">
                <input id="email" class="form-control" placeholder="email" name="email" type="text" value="">
            </div>
            <div class="col">
                <label class="visually-hidden" for="company">Company</label>
                {{company_dropdown(request.args.get("company"))}}
            </div>
            {{sort_filter(cols=[("first_name","first_name"),("last_name","last_name"),("email","email"),("company_name","company_name")])}}
            <div class="col">
                <input id="limit" class="form-control" placeholder="limit" name="limit" type="int" value="10">
            </div>
            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
          <tr class="text-capitalize">
            {% for col in allowed_columns %}
            <th>{{ col[1] }}</th>
            {% endfor %}
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rows %}
          <tr>
            {% for col in allowed_columns %}
            <td>{{ row[col[0]] }}</td>
            {% endfor %}
            <td>
              <a href="/employee/edit?id={{ row['id'] }}">Edit</a>
              <a href="/employee/delete?id={{ row['id'] }}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        {% else %}
        <tbody>
          <tr>
            <td colspan="100%">No results to show</td>
          </tr>
        </tbody>
        {% endif %}
      </table>
</div>
{% endblock %}

BusinessManagement/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO replace my ucid mt85 with your ucid in the below a tag #}
        <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-al762</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO fill in the relevant hrefs using url_for() #}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- company dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/company/search">Search</a></li>
                        <li><a class="dropdown-item" href="/company/add">Add</a></li>

                    </ul>
                </li>
                <!-- employee dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Employee
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/employee/search">Search</a></li>
                        <li><a class="dropdown-item" href="/employee/add">Add</a></li>
                    </ul>
                </li>
                <!-- admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/admin/import">Import</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

BusinessManagement/templates/sort_filter.html
{# TODO DO NOT EDIT #}
{% macro sort_filter(cols=[]) %}
<div class="col">
    <label class="visually-hidden" for="col">Field</label>
    <select class="form-select" id="col" name="column" value="{{request.args.get('column', '')}}">
        <option value="">Field...</option>
        {# hint expects a list of tuples representing (value, label) #}
        {% for v,l in cols %}
        <option {{'selected' if v==request.args.get('column', '' )}} value="{{v}}">{{l | capitalize}}</option>
        {% endfor %}
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="order">Order</label>
    <select class="form-select" id="order" name="order" value="{{request.args.get('order', 'asc')}}">
        <option {{'selected' if request.args.get('order')=='asc' }} value="asc">Up</option>
        <option {{'selected' if request.args.get('order')=='desc' }} value="desc">Down</option>
    </select>
</div>
{% endmacro %}

BusinessManagement/templates/upload.html
{# TODO DO NOT EDIT #}
{% extends "layout.html" %}
{% block title %}Import Data{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Import Data</div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Search File</label>
                <input class="form-control" id="n" name="file" type="file" />
            </div>
            <input type="submit" class="btn btn-primary" value="Import" />
        </form>
    </div>
</div>
{% endblock %}